name: Deploy with Firebase

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@master
      - name: Install node
        uses: actions/setup-node@master
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy with Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          # see via cmd: firebase login:ci
          FIREBASE_TOKEN: ${{ secrets.VITE_API_KEY }}
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{env.VITE_AUTH_DOMAIN}}
          VITE_DATABASEURL: ${{env.VITE_DATABASEURL}}
          VITE_PROJECT_ID: ${{env.VITE_PROJECT_ID}}
          VITE_STORAGE_BUCKET: ${{env.VITE_STORAGE_BUCKET}}
          VITE_MESSAGING_SENDER_ID: ${{env.VITE_MESSAGING_SENDER_ID}}
          VITE_APP_ID: ${{env.VITE_APP_ID}}